# Generated by Django 3.2 on 2021-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=60)),
                ('short', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
