# Generated by Django 3.2 on 2021-04-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_webservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='short',
            field=models.CharField(blank=True, default='', max_length=60, unique=True),
        ),
    ]
