# Generated by Django 3.2 on 2021-04-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_webservice', '0002_alter_links_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='short',
            field=models.CharField(default='zru74efV67IlvdeRulKBFBwl10KAFiVr', max_length=60, unique=True),
        ),
    ]
