# Generated by Django 3.2 on 2021-04-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_webservice', '0003_alter_links_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='short',
            field=models.CharField(default='VhFWxZpkCYUrDZUgbSiOOo2gM9ZnqOVy', max_length=60, unique=True),
        ),
    ]
